parameters:
  failOnError: false
  failOnWarning: false
  progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters:
      scanOnlyInScope: false

  - type: spider
    parameters:
      contextName: Default Context
      url: ${{ env.APP_URL }}
      maxDuration: 5

  - type: script
    parameters:
      action: run
      type: stand-alone
      engine: Oracle Nashorn
      name: generate-sarif.js
      file: .zap/generate-sarif.js

  - type: report
    parameters:
      template: traditional-html
      reportDir: zap-results
      reportFile: zap-report.html
