---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hour-app
  labels:
    app: hour-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hour-app
  template:
    metadata:
      labels:
        app: hour-app
    spec:
      containers:
        - name: hour-app
          image: "__IMAGE__"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: hour-app
spec:
  type: NodePort
  selector:
    app: hour-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
