env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://hour-app.wittypond-8701d159.westeurope.azurecontainerapps.io
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://hour-app.wittypond-8701d159.westeurope.azurecontainerapps.io
  type: spider
- parameters:
    maxDuration: 60
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
